/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./../components/backTop/index.vue')['default']
    PageBox: typeof import('./../components/pageBox/index.vue')['default']
    PageFooter: typeof import('./../components/pageFooter/index.vue')['default']
    PageHead: typeof import('./../components/pageHead/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
